#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="qlbhat")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBAIHAT(BAIHAT instance);
    partial void UpdateBAIHAT(BAIHAT instance);
    partial void DeleteBAIHAT(BAIHAT instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::QLBH.Properties.Settings.Default.qlbhatConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BAIHAT> BAIHATs
		{
			get
			{
				return this.GetTable<BAIHAT>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BAIHAT")]
	public partial class BAIHAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mabaihat;
		
		private string _tenbaihat;
		
		private string _matheloai;
		
		private string _maalbum;
		
		private string _macasi;
		
		private string _matacgia;
		
		private string _mahangsanxuat;
		
		private string _loibaihat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmabaihatChanging(string value);
    partial void OnmabaihatChanged();
    partial void OntenbaihatChanging(string value);
    partial void OntenbaihatChanged();
    partial void OnmatheloaiChanging(string value);
    partial void OnmatheloaiChanged();
    partial void OnmaalbumChanging(string value);
    partial void OnmaalbumChanged();
    partial void OnmacasiChanging(string value);
    partial void OnmacasiChanged();
    partial void OnmatacgiaChanging(string value);
    partial void OnmatacgiaChanged();
    partial void OnmahangsanxuatChanging(string value);
    partial void OnmahangsanxuatChanged();
    partial void OnloibaihatChanging(string value);
    partial void OnloibaihatChanged();
    #endregion
		
		public BAIHAT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mabaihat", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mabaihat
		{
			get
			{
				return this._mabaihat;
			}
			set
			{
				if ((this._mabaihat != value))
				{
					this.OnmabaihatChanging(value);
					this.SendPropertyChanging();
					this._mabaihat = value;
					this.SendPropertyChanged("mabaihat");
					this.OnmabaihatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenbaihat", DbType="NVarChar(100)")]
		public string tenbaihat
		{
			get
			{
				return this._tenbaihat;
			}
			set
			{
				if ((this._tenbaihat != value))
				{
					this.OntenbaihatChanging(value);
					this.SendPropertyChanging();
					this._tenbaihat = value;
					this.SendPropertyChanged("tenbaihat");
					this.OntenbaihatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matheloai", DbType="NVarChar(50)")]
		public string matheloai
		{
			get
			{
				return this._matheloai;
			}
			set
			{
				if ((this._matheloai != value))
				{
					this.OnmatheloaiChanging(value);
					this.SendPropertyChanging();
					this._matheloai = value;
					this.SendPropertyChanged("matheloai");
					this.OnmatheloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maalbum", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maalbum
		{
			get
			{
				return this._maalbum;
			}
			set
			{
				if ((this._maalbum != value))
				{
					this.OnmaalbumChanging(value);
					this.SendPropertyChanging();
					this._maalbum = value;
					this.SendPropertyChanged("maalbum");
					this.OnmaalbumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macasi", DbType="NVarChar(50)")]
		public string macasi
		{
			get
			{
				return this._macasi;
			}
			set
			{
				if ((this._macasi != value))
				{
					this.OnmacasiChanging(value);
					this.SendPropertyChanging();
					this._macasi = value;
					this.SendPropertyChanged("macasi");
					this.OnmacasiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matacgia", DbType="NVarChar(50)")]
		public string matacgia
		{
			get
			{
				return this._matacgia;
			}
			set
			{
				if ((this._matacgia != value))
				{
					this.OnmatacgiaChanging(value);
					this.SendPropertyChanging();
					this._matacgia = value;
					this.SendPropertyChanged("matacgia");
					this.OnmatacgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahangsanxuat", DbType="NVarChar(50)")]
		public string mahangsanxuat
		{
			get
			{
				return this._mahangsanxuat;
			}
			set
			{
				if ((this._mahangsanxuat != value))
				{
					this.OnmahangsanxuatChanging(value);
					this.SendPropertyChanging();
					this._mahangsanxuat = value;
					this.SendPropertyChanged("mahangsanxuat");
					this.OnmahangsanxuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loibaihat", DbType="NVarChar(MAX)")]
		public string loibaihat
		{
			get
			{
				return this._loibaihat;
			}
			set
			{
				if ((this._loibaihat != value))
				{
					this.OnloibaihatChanging(value);
					this.SendPropertyChanging();
					this._loibaihat = value;
					this.SendPropertyChanged("loibaihat");
					this.OnloibaihatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
